### ISSUE TITLE
problem with spatial from clean install

### ISSUE THREAD

**Issue by bhillmann** [shilad/wikibrain#207]
I ran a clean install with a git clone and a maven install on a Debian box and received the error message below. Probably something small but I'm trying to do a quick project and a bit rusty on my Java.

[INFO] Reactor Summary:
[INFO] 
[INFO] WikiBrain parent ................................... SUCCESS [  0.514 s]
[INFO] wikibrain-utils .................................... SUCCESS [  1.150 s]
[INFO] wikibrain-matrix ................................... SUCCESS [  0.185 s]
[INFO] wikibrain-core ..................................... SUCCESS [ 11.115 s]
[INFO] wikibrain-download ................................. SUCCESS [  0.229 s]
[INFO] wikibrain-lucene ................................... SUCCESS [  0.279 s]
[INFO] wikibrain-phrases .................................. SUCCESS [  0.313 s]
[INFO] wikibrain-parser ................................... SUCCESS [  0.186 s]
[INFO] wikibrain-wikidata ................................. SUCCESS [  0.174 s]
[INFO] wikibrain-mapper ................................... SUCCESS [  0.198 s]
[INFO] wikibrain-sr ....................................... SUCCESS [  1.303 s]
[INFO] wikibrain-spatial .................................. FAILURE [  1.014 s]
[INFO] wikibrain-loader ................................... SKIPPED
[INFO] wikibrain-integration-tests ........................ SKIPPED
[INFO] wikibrain-pageview ................................. SKIPPED
[INFO] wikibrain-cookbook ................................. SKIPPED
[INFO] wikibrain .......................................... SKIPPED
[INFO] wikibrain-all ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.262 s
[INFO] Finished at: 2014-08-25T22:34:10-05:00
[INFO] Final Memory: 33M/172M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wikibrain-spatial: Compilation failure
[ERROR] /media/tagg/wikibrain/wikibrain-spatial/src/main/java/org/wikibrain/spatial/core/dao/postgis/PostGISSpatialNeighborDao.java:[27,16] cannot find symbol
[ERROR] symbol:   class Sort
[ERROR] location: package sun.misc
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wikibrain-spatial

**Comment by shilad** [comment]
Closing because I haven't heard any other complaints since the fix went out.
