### ISSUE TITLE
Running out of heap space in simple english import with spatial data selected

### ISSUE THREAD

**Issue by daredevil82** [shilad/wikibrain#215]
I'm running this on a '13 MacBook Pro with a SSD and 16GB RAM with the 0.4.1 jar + dependencies.  All wikibrain interaction was done through the GUI via executing `java -jar wikibrain-....-0.4.1.jar` at the command line.

I have Postgres and PostGIS installed with the databases configured.  This exception occurred on two separate import attempts, with memory set to 5G and 10G, respectively.  Each time, I get 

    "Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
    Exception in thread "AWT-EventQueue-0" Exception in thread "Thread-14"   
        java.lang.OutOfMemoryError: Java heap space
    java.lang.OutOfMemoryError: Java heap space
    Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

Has anyone tried doing a fresh re-import as part of the build process?

**Comment by shilad** [comment]
This issue should have been fixed in release 0.5.0. I'm going to close it, but let me know if you still see problems!
