### ISSUE TITLE
The downloader should use a multithread implement for better performance

### ISSUE THREAD

**Issue by monkey2000** [shilad/wikibrain#240]

**Comment by shilad** [comment]
Thanks for the suggestion! It's easy to do this, but last time I checked Wikipedia servers blocked you if you tried to open multiple download streams simultaneously. Do you have reason to believe this isn't true?

**Comment by monkey2000** [comment]
The official repo said that max per-ip connections to 2. Also, there are many mirrors. I think fetch from multi-mirrors can solve this problem.
See also: http://dumps.wikimedia.org/

**Comment by monkey2000** [comment]
The mirrors list can be found here: http://dumps.wikimedia.org/mirrors.html

**Comment by monkey2000** [comment]
The official repo said that max per-ip connections is 2. Also, there are many mirrors. I think fetch from multi-mirrors can solve this problem.
See also: http://dumps.wikimedia.org/

**Comment by monkey2000** [comment]
The mirrors list can be found here: http://dumps.wikimedia.org/mirrors.html
