### ISSUE TITLE
Use relative file path in DumpLoader.load()

### ISSUE THREAD

**Issue by cheetah90** [shilad/wikibrain#249]
On [line 82](https://github.com/shilad/wikibrain/blob/9274ffce8b3dcb32d26869f5e2a076eb3d7e2d72/wikibrain-loader/src/main/java/org/wikibrain/loader/DumpLoader.java#L82), use relative path than the absolute path, in case "wiki" is part of the parent file path.

**Comment by shilad** [comment]
Should be fixed in f8ab50f085269ab096d4f92677686df81bfba6b3
